### ISSUE TITLE
How to set the warm-up period when using the XAJ model?

### ISSUE THREAD

**Issue by lilyomo** [CUG-hydro/hydroTools#2]
This project is  excellent. Your work is very helpful.
I have a question to ask: How to set the warm-up period when using the XAJ model? The warm-up period is very important for hydrological models.

Thank you.

**Comment by kongdd** [comment]
可以参考MarrMot的做法，前两年的数据不参与率定，这两年即为预热期。这里要修改目标函数
https://github.com/CUG-hydro/hydroTools/blob/master/R/calib_XAJ.R#L26

**Comment by lilyomo** [comment]
@kongdd 好的，谢谢。我试一下。
